### ISSUE TITLE
Restructure docs to elevate the PRO features

### ISSUE THREAD

**Issue by sabbyanandan** [pivotal-cf/docs-spring-cloud-dataflow-k8s#31]
Perhaps right below "Developer Guide" , we can add another link: "Pro Features", and under that we can chain all the commercial-only features.

![image](https://user-images.githubusercontent.com/1562654/100898914-1bac6400-3476-11eb-8953-2a93847ad2ba.png)

**Comment by trisberg** [comment]
Done: https://docs.pivotal.io/scdf-k8s/1-2/pro-features/index.html
