### ISSUE TITLE
Can we provide instructions on cleaning up DataFlow pro 

### ISSUE THREAD

**Issue by cppwfs** [pivotal-cf/docs-spring-cloud-dataflow-k8s#35]
For Devs that are experimenting with PRO, we probably want to have instructions on cleanup when their done.
i.e. something like 

# Cleanup
## Find all components that we need to Cleanup
kubectl get all

# Cleanup SCDF bits (you will need to update the services below, this is just an example)
kubectl delete replicaset.apps/scdf-server-bff8bc77c deployment.apps/scdf-server service/scdf-server

# Cleanup Skipper
kubectl delete deployment.apps/skipper service/skipper

# Cleanup Rabbitmq
kubectl delete statefulset.apps/rabbitmq service/rabbitmq-headless service/rabbitmq

# Cleanup postgres
kubectl delete statefulset.apps/postgresql service/postgresql-headless service/postgresql

**Comment by trisberg** [comment]
How did you install it?

If you use `./bin/install-dev.sh` then you can use `./bin/uninstall-dev.sh`

Documented here: http://docs-pcf-staging.cfapps.io/scdf-k8s/1-2/installing-scdf-for-kubernetes.html#uninstall-scdf-for-k8s-dev

**Comment by sabbyanandan** [comment]
We should just stick with the install/uninstall scripts, and it works really nicely!

**Comment by cppwfs** [comment]
Closing as invalid.  Thanks!
