### ISSUE TITLE
1.3.0 GA release

### ISSUE THREAD

**Issue by sabbyanandan** [pivotal-cf/docs-spring-cloud-dataflow-k8s#40]
- [ ] Add release notes
- [ ] Update 'Product Snapshot'
- [ ] Add new branch to staging
- [ ] Publish new branch
- [ ] Switch all the RC references in the version table (1.3.0, 2.7.0, and 2.8.0):
![image](https://user-images.githubusercontent.com/1562654/121919143-925ecf80-cceb-11eb-9dda-c14c8deb5368.png)

**Comment by sabbyanandan** [comment]
cc: @trisberg

**Comment by fifthposition** [comment]
1.3.0 documentation is at https://docs.pivotal.io/scdf-k8s/1-3/
