### ISSUE TITLE
Update documentation for k8s versions

### ISSUE THREAD

**Issue by corneil** [pivotal-cf/docs-spring-cloud-dataflow-k8s#51]
On the page: [https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations](https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations) please add k8s 1.23 and 1.24 as supported and remove 1.18.

**Comment by fifthposition** [comment]
Updated the section: https://docs.vmware.com/en/VMware-Spring-Cloud-Data-Flow-for-Kubernetes/1.4/scdf-k8s/GUID-index.html#general-limitations
