### ISSUE TITLE
Update docs for 1.5.2 release

### ISSUE THREAD

**Issue by corneil** [pivotal-cf/docs-spring-cloud-dataflow-k8s#52]
# Notable changes
## Library updates

* Spring Boot `2.7.9`
* Spring Cloud `2021.0.6`
* Spring Framework `5.3.25`

## Kubernetes
* Added ability to fully configure pod and container security contexts.
* Container security context is propagated to init container and additional containers.

**Comment by fifthposition** [comment]
Added the version 1.5 release notes. They are now available on staging.
